//
//  ProductDetailData.swift
//  nikeAppClone
//
//  Created by Sunghyun Kim on 1/29/26.
//

import SwiftUI

let productDetails: [ProductDetail] = [
    .init(id: "Nike01", name: "Nike Everyday Plus Cushioned", category: "Training Crew Socks", longDescription: "The Nike Everyday Plus Cushioned Socks bring comfort to your workout with extra cushioning under the heel and forefoot and a snug, supportive arch band. Sweat-wicking power and breathability up top help keep your feet dry and cool to help push you through that extra set.", info: "• Shown: Multi-Color\n• Style: SX6897-965", price: "US$10", image: "image-1", imageDetail1: "productDetail2", imageDetail2: "productDetail3", imageDetail3: "productDetail4", copyTitle: "LEGENDARY STYLE REFINED.", copyDescription: "The Nike Everyday Plus Cushioned Socks bring comfort to your workout with extra cushioning under the heel and forefoot and a snug, supportive arch band. Sweat-wicking power and breathability up top help keep your feet dry and cool to help push you through that extra set.", benefits: "• Cushioning under the forefoot and heel helps soften the impact of your workout.\n• Dri-FIT technology helps your feet stay dry and comfortable.\n• Band around the arch feels snug and supportive.\n• Breathable knit pattern on top adds ventilation.\n• Reinforced heel and toe are made to last.", productDetails: "• Fabric: 61-67% cotton/30-36% \npolyester/2% spandex/1% nylon\n• Machine wash\n• Imported\n• Note: Material percentages may vary slightly depending on color. Check label for actual content.\n• Shown: Multi-Color\n• Style: SX6897-965"),
    
    .init(id: "Nike02", name: "Nike Everyday Plus Cushioned", category: "Training Crew Socks", longDescription: "The Nike Everyday Plus Cushioned Socks bring comfort to your workout with extra cushioning under the heel and forefoot and a snug, supportive arch band. Sweat-wicking power and breathability up top help keep your feet dry and cool to help push you through that extra set.", info: "• Shown: Multi-Color\n• Style: SX6897-965", price: "US$10", image: "image-2", imageDetail1: "productDetail2", imageDetail2: "productDetail3", imageDetail3: "productDetail4", copyTitle: "LEGENDARY STYLE REFINED.", copyDescription: "The Nike Everyday Plus Cushioned Socks bring comfort to your workout with extra cushioning under the heel and forefoot and a snug, supportive arch band. Sweat-wicking power and breathability up top help keep your feet dry and cool to help push you through that extra set.", benefits: "• Cushioning under the forefoot and heel helps soften the impact of your workout.\n• Dri-FIT technology helps your feet stay dry and comfortable.\n• Band around the arch feels snug and supportive.\n• Breathable knit pattern on top adds ventilation.\n• Reinforced heel and toe are made to last.", productDetails: "• Fabric: 61-67% cotton/30-36% \npolyester/2% spandex/1% nylon\n• Machine wash\n• Imported\n• Note: Material percentages may vary slightly depending on color. Check label for actual content.\n• Shown: Multi-Color\n• Style: SX6897-965"),
    
    .init(id: "Nike03", name: "Nike Everyday Plus Cushioned", category: "Training Crew Socks", longDescription: "The Nike Everyday Plus Cushioned Socks bring comfort to your workout with extra cushioning under the heel and forefoot and a snug, supportive arch band. Sweat-wicking power and breathability up top help keep your feet dry and cool to help push you through that extra set.", info: "• Shown: Multi-Color\n• Style: SX6897-965", price: "US$10", image: "image-3", imageDetail1: "productDetail2", imageDetail2: "productDetail3", imageDetail3: "productDetail4", copyTitle: "LEGENDARY STYLE REFINED.", copyDescription: "The Nike Everyday Plus Cushioned Socks bring comfort to your workout with extra cushioning under the heel and forefoot and a snug, supportive arch band. Sweat-wicking power and breathability up top help keep your feet dry and cool to help push you through that extra set.", benefits: "• Cushioning under the forefoot and heel helps soften the impact of your workout.\n• Dri-FIT technology helps your feet stay dry and comfortable.\n• Band around the arch feels snug and supportive.\n• Breathable knit pattern on top adds ventilation.\n• Reinforced heel and toe are made to last.", productDetails: "• Fabric: 61-67% cotton/30-36% \npolyester/2% spandex/1% nylon\n• Machine wash\n• Imported\n• Note: Material percentages may vary slightly depending on color. Check label for actual content.\n• Shown: Multi-Color\n• Style: SX6897-965"),
    
        .init(id: "Nike04", name: "Nike Everyday Plus Cushioned", category: "Training Crew Socks", longDescription: "The Nike Everyday Plus Cushioned Socks bring comfort to your workout with extra cushioning under the heel and forefoot and a snug, supportive arch band. Sweat-wicking power and breathability up top help keep your feet dry and cool to help push you through that extra set.", info: "• Shown: Multi-Color\n• Style: SX6897-965", price: "US$10", image: "productDetail1", imageDetail1: "productDetail2", imageDetail2: "productDetail3", imageDetail3: "productDetail4", copyTitle: "LEGENDARY STYLE REFINED.", copyDescription: "The Nike Everyday Plus Cushioned Socks bring comfort to your workout with extra cushioning under the heel and forefoot and a snug, supportive arch band. Sweat-wicking power and breathability up top help keep your feet dry and cool to help push you through that extra set.", benefits: "• Cushioning under the forefoot and heel helps soften the impact of your workout.\n• Dri-FIT technology helps your feet stay dry and comfortable.\n• Band around the arch feels snug and supportive.\n• Breathable knit pattern on top adds ventilation.\n• Reinforced heel and toe are made to last.", productDetails: "• Fabric: 61-67% cotton/30-36% \npolyester/2% spandex/1% nylon\n• Machine wash\n• Imported\n• Note: Material percentages may vary slightly depending on color. Check label for actual content.\n• Shown: Multi-Color\n• Style: SX6897-965")
]
